@startuml 接收文件merge
start
:拼接最终文件存储位置;
:合并文件块;
  note right
    调用服务mergeFileChunk
  end note
:获取文件块列表;
:排序文件块;
:转为绝对路径;
fork
  :pipeStream();
fork again
  :pipeStream();
fork again
  :pipeStream();
fork again
  :...;  
end fork
note right
  pipeStream core code
  ====
  const readStream = fse.createReadStream(filePath)
  readStream.on("end", () => {
    // 删除文件
    fse.unlinkSync(filePath)
    resolve()
  })
  readStream.pipe(writeStream)
end note
:返回上传成功;
stop
@enduml