@startmindmap 文件校验

* 文件校验
** 校验大小
*** file的size属性
** 校验类型
*** 文件原数据
**** 类型规范
***** png以<b>89 50 4E 47 0D 0A 1A 0A</b>开头
***** gif以<b>47 49 46 38 39 61</b>或<b>47 49 46 38 37 61</b>开头
***** jpg开头<b>FF D8</b>，结尾<b>FF D9</b>
**** 图片宽高
*** 后缀名
@endmindmap
